# Generated by Django 2.1.4 on 2018-12-17 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0002_auto_20181217_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='last edit')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='title')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.Contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
