/' = = = = = = = ATTRIBUTES = = = = = = = '/
class user{
    att(1st_name,String,VARCHAR(30) NOT NULL)
    att(name,String,VARCHAR(30) NOT NULL)
    att(email,String,VARCHAR(254) NOT NULL)
    att(password,String,VARCHAR(128) NOT NULL)
    att(username,String,VARCHAR(150) NOT NULL)
    `django.auth.models.User`
}

class contact{
    att(name,String,VARCHAR(30) NOT NULL)
    att(1st_name,String,VARCHAR(30) NOT NULL)
    att(birthday,Date,DATETIME NOT NULL)
    att(creation,Date,DATETIME NOT NULL)
    att(edition,Date,DATETIME NOT NULL)
    att(mail1,String,VARCHAR(40) NULL)
    att(mail2,String,VARCHAR(40) NULL)
    att(phone1,String,VARCHAR(10) NOT NULL)
    att(phone2,String,VARCHAR(10) NOT NULL)
    … : uses Vcards fields
}

class tag{
    att(name,String,VARCHAR(10) NOT NULL)
    att(desc,String,TEXT NOT NULL)
}

class entry{
    att(label,String,VARCHAR(20) NOT NULL)
    att(desc,String,TEXT NOT NULL)
    att(creation,Date,DATETIME NOT NULL)
    att(edition,Date,DATETIME NOT NULL)
}

class archive{
    att(label,String,VARCHAR(20) NOT NULL)
    att(desc,String,TEXT NOT NULL)
    att(creation,Date,DATETIME NOT NULL)
    att(edition,Date,DATETIME NOT NULL)
}

class tag_entry{
    att(name,String,VARCHAR(10) NOT NULL)
    att(desc,String,TEXT NOT NULL)
}
