/' = = = = = = = CLASSES = = = = = = = '/
class contact
class entry
class tag
class user


/' = = = = = = = RELATIONS = = = = = = = '/
rel(contact,1,--,*,entry)
rel(contact,*,--,1,user)
rel(user,*,-,*,entry)
rel(tag,*,-,*,tag)
