/' = = = = = = = CLASSES = = = = = = = '/
class contact
class entry
class tag
class user <<auth>>


/' = = = = = = = RELATIONS = = = = = = = '/
rel(contact,1,--,*,entry)
rel(contact,*,-,*,tag)
rel(tag,*,--,*,entry)
rel(tag,*,-,*,tag)
rel(contact,*,--,1,user)
rel(user,*,-,*,entry)
