@startuml

title Domaine fonctionnel

/' = = = = = = = STYLE = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp13/master/doc/data_model/style.iuml

/' = = = = = = = MACRO = = = = = = = '/
!define rel(a,b,c,d,e) a "b" c "d" e
!define rea(a,b,c,d) (a, b) c d
!define att(n,u,s) n : u

/' = = = = = = = ASSOCIATIONS = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp13/master/doc/data_model/associations.iuml

/' = = = = = = = CLASSES = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp13/master/doc/data_model/classes.iuml

/' = = = = = = = ATTRIBUTES = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp13/master/doc/data_model/attributes.iuml

/' = = = = = = = LEGEND = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp13/master/doc/data_model/legend.iuml

@enduml
