@startuml

title Functionnal domain\n <i>(draft)</i>\n

/' = = = = = = = STYLE = = = = = = = '/
' skinparam monochrome true
skinparam linetype ortho
hide empty methods
hide <<assoc>> circle
skinparam class {
    BackgroundColor<<assoc>> lightblue
}

/' = = = = = = = MACRO = = = = = = = '/
' !define rel(a,b,c,d,e) a c e

!define rel(a,b,c,d,e) a "b" c "d" e
!define rea(a,b,c,d) (a, b) c d

/' = = = = = = = CLASSE = = = = = = = '/
' !includeurl https://raw.githubusercontent.com/freezed/ocp13/master/src-puml/classes.iuml

class user
class contact
class tag
class log
class entry
class tag_entry


/' = = = = = = = RELATION = = = = = = = '/
rel(user,1,-,*,contact)
rel(contact,1,-,*,log)
rel(contact,1,--,*,entry)
rel(tag,*,-,*,contact)
rel(user,1,--,*,log)
rel(log,1,--,*,entry)
rel(tag_entry,*,-,*,entry)
rel(tag,*,-,*,tag)
rel(tag_entry,*,-,*,tag_entry)

/' = = = = = = = ATTRIBUTE = = = = = = = '/

class user{
    <i>Utilisateur</i>\n<i>du service</i>
}
class contact{
    <i>Contact de</i>
    <i>l'utilisateur</i>
}
class tag{
    <i>tag des</i>
    <i>contacts</i>
}
class log{
    <i>Historique</i>
    <i>d'un contact</i>
}
class entry{
    <i>Entrée</i>
    <i>d'historique</i>
}
class tag_entry {
    <i>Tag des</i>
    <i>entrée</i>
    <i>d'historique</i>
}


/' = = = = = = = LEGEND = = = = = = = '/
legend
    Version 1
endlegend

@enduml
