@startuml

title Modèle physique de données

/' = = = = = = = STYLE = = = = = = = '/
skinparam linetype ortho
left to right direction
hide empty methods
hide <<assoc>> circle
hide <<auth>> circle
skinparam class {
    BackgroundColor<<assoc>> lightblue
    BackgroundColor<<auth>> lightgreen
}

/' = = = = = = = MACRO = = = = = = = '/
!define rel(a,b,c,d,e) a c e
!define rea(a,b,c,d) (a, b) c d
!define pyk(n,t="INT NOT NULL UNSIGNED") <font color="red">PK:<b>n</b> <size:09>[t]</size></font>
!define fnk(n,r,t="INT NOT NULL UNSIGNED") <font color="blue">FK:<b>n</b> <size:09>[t]</size></font>
!define att(n,u,s) {field} <b>n</b> [s]

/' = = = = = = = ASSOCIATIONS = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp13/wip-doc/doc/data_model/associations.iuml

/' = = = = = = = KEYS = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp13/wip-doc/doc/data_model/keys.iuml

/' = = = = = = = ATTRIBUTES = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp13/wip-doc/doc/data_model/attributes.iuml

/' = = = = = = = CLASSES = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp13/wip-doc/doc/data_model/classes.iuml

/' = = = = = = = LEGEND = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp13/wip-doc/doc/data_model/legend.iuml

@enduml
